ISP = ''
PROMISED_DL = 0
PROMISED_UP = 0
TWITTER_USERNAME = ''
TWITTER_PASSWORD = ''
BROWSER = 'Firefox'
AVG_SPEED = 0
START_TWEET = 'Hey, ! Why is my internet speed'
END_TWEET = 'When I pay for 0dl/0up?'
