ISP = 'ejiz'
PROMISED_DL = 4
PROMISED_UP = 4
TWITTER_USERNAME = 'zr'
TWITTER_PASSWORD = 'rtzr'
BROWSER = 'Firefox'
AVG_SPEED = 45
START_TWEET = 'Hey, ejiz! Why is my internet speed'
END_TWEET = 'When I pay for 4dl/4up?'
